baseURL = 'https://tristanbay.com'
locale = 'en-us'
title = 'Tristan Bay Website'
theme = 'tristanbay'

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      strikethrough = false
      [markup.goldmark.extensions.extras]
        [markup.goldmark.extensions.extras.subscript]
          enable = true
        [markup.goldmark.extensions.extras.superscript]
          enable = true
        [markup.goldmark.extensions.extras.delete]
          enable = true

[params]
  name = 'Tristan Bay'
  email = 'tristanbaymusic@gmail.com'
  
  favicon = "favicon.ico"

  #list items
  datesinlist = false
  sayreleased = false
  buttonlist = true

  #page items
  visiblepage = true
