baseURL = 'https://tristanbay.com'
languageCode = 'en-us'
title = 'Tristan Bay Website'
theme = 'tristanbay'

[params]
  name = 'Tristan Bay'
  email = 'tristanbaymusic@gmail.com'
  
  favicon = "/favicon.ico"

  #list items
  datesinlist = false
  sayreleased = false
  buttonlist = true

  #page items
  visiblepage = true
